### PR TITLE
fix the problem that underStatusBarView is nil.

### LINKED ISSUE #4: Copy from Example but crash
hello, I installed through cocoa pods.
my Xcode is Version 7.3 (7D175)

This is my code:
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        let message = Message(text: "You have an alert")
        NotificationBanner.showMessage(message)
    }
but i get: fatal error: unexpectedly found nil while unwrapping an Optional value.
And I trying to track the bug, it always crash at NotificationBanner.swift line:234
`override public var barTintColor: UIColor? {
        didSet {
            underStatusBarView.backgroundColor = barTintColor?.colorWithAlphaComponent(0.85)
        }
    }`
It's my first time to post something here, and i don't know how to insert code and image correctly, sorry for everyone.
Can anybody help me?

### PR DESCRIPTION
**Pull request by lockys**
I did some small fix, and bumped the version to `0.1.3`.
I have no experience of developing Pod, let me know if there are problem. 
Thank you, great work :)
resolve #4

### CODE REVIEW

**Comment by charliewilliams** [comment]
Thanks for this! I'm working on a bigger update and will pull this into it.

**Comment by lockys** [comment]
Great! Looking forward to your update :)
I am using it in my app hah.
By the way, @charliewilliams 
if you could put the GIF demo of this module, we can decide if this module meets our needs at the first glance.
Thanks your awesome work.

**Comment by charliewilliams** [comment]
Can you pull 0.2.0 and confirm whether this fixes your issue?

0.2.0 contains breaking changes but they should be just class renaming— easy to fix.

**Comment by lockys** [comment]
Okay, I will try it later.

---

UPDATED @charliewilliams 
There is no crash of `0.2.0`. But the style is a little bit weird.
Could you share your screenshot with me?

fullsizerender
ran on iOS 8.1 Jailbroken device.

I am using the following code with timer.

``` swift
let message = Message(text: "test", displayDuration: 6)
NotificationBanner.showMessage(message)
```

**Pull request merged**
